version: '3'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - KEY=${KEY}
      - ID=${ID}
      - SECRET=${SECRET}
    command: gunicorn  main:app --bind=0.0.0.0:5000